[package]
name = "repository"
version = "0.1.0"
edition = "2018"

[dependencies]
once_cell = "1.8"
tiberius = { version = "0.6", features = ["rust_decimal", "chrono"] }
tokio-util = { version = "0.6", features = ["compat"] }
tokio = { version = "1.11", features = ["full"] }
serde = "1.0"
